### ISSUE TITLE
IO Error in Windows

### ISSUE THREAD

**Issue by nsathishk** [Ucnt/aws-s3-downloader#2]
I got "IOError: (Errno 0) Error" in Windows when trying to download the Bucket XML.
Based on this answer in SO about Python in Windows requiring " intervening fflush, fsetpos, fseek, or rewind operation" "between reading and writing"
[https://stackoverflow.com/questions/19283118/python-ioerror-errno-0-error-what-is-triggering-this-error-in-my-code](https://stackoverflow.com/questions/19283118/python-ioerror-errno-0-error-what-is-triggering-this-error-in-my-code)
I was able to edit download_bucket_public.py to include f.seek(0,2) before the write() line in save_xml() and it worked downloading all bucket lists past first 1000 objects.

**Comment by Ucnt** [comment]
Just added it.  Can you do a git pull and try again?  

Tested in Linux (where I wrote it) and no issues.  If that works, I'll add it to the other files as well.

**Comment by nsathishk** [comment]
Yes, -x worked.  Issue can be closed.
