### ISSUE TITLE
Download Stops on Files with No Extension

### ISSUE THREAD

**Issue by TechXPlays** [Ucnt/aws-s3-downloader#3]
Realized this last night downloading some files... some of the file keys were named something like 

logs/1h1o3i4ha90234jklalsik902830

no extension, just a file, and it crashes the downloader everytime. I'm no python guy, so I don't really know how to even begin to fix it. For now, I've just excluded the logs folder from my downloads as a work around

Other than that, this tool is amazing, thanks for making it

**Comment by Ucnt** [comment]
Great feedback.  Let me look at the code when I get home.

**Comment by Ucnt** [comment]
Mind providing an example bucket?

**Comment by Ucnt** [comment]
I tried on qnapsp which has files like https://qnapsp.s3.amazonaws.com/logs/2013-12-17-19-16-58-8C73558DE82ABE69 and it worked.

Could you try and maybe copy the error you are getting.  It should have a line number and start with:

"Traceback (most recent call last):"

**Comment by TechXPlays** [comment]
The bucket server I've been downloading from is over 1.8million keys in size, somewhere around 1803000 is the furthest I've seen this go without crashing. The server this is on is public and does not require login credentials of any kind to view

The bucket server name I'm using is cie-fueled-racing-cdn. The log/askl213940salkd whatever files are somewhere past the 1 million point. I've tried again doing -i logs, it suddenly stopped doing it I realized (after 3 hours of downloading...). Below are 2 screen shots of the logs on the bucket server, and an error that just randomly occurs and it stops

this first SS is the logs on the bucket server, got to this manually with
?list-type=2&start-after=log/
http://techx.onl/pic/Logs.png

This is a SS of the errors specifically that just randomly pops up. Maybe its unrelated to this issue, but its very close to the same error I got when it crashed first few times on the logs
http://techx.onl/pic/log2.png

Would have responded sooner, just got home, sorry! lol

**Comment by Ucnt** [comment]
Oddly:

1) Getting a 404 on the png links.

2) I'm able to download the log files, e.g. below.

  Downloading https://s3.amazonaws.com/cie-fueled-racing-cdn/logs/2013-07-26-01-34-04-782EE10CC6B5A2AC
    FINISHED
  Downloading https://s3.amazonaws.com/cie-fueled-racing-cdn/logs/2013-07-26-01-36-17-69A1EE8298798C9B
    FINISHED
  Downloading https://s3.amazonaws.com/cie-fueled-racing-cdn/logs/2013-07-26-01-37-28-0F5BE0495F672ABD
    FINISHED
  Downloading https://s3.amazonaws.com/cie-fueled-racing-cdn/logs/2013-07-26-01-37-28-96199DAB1962E77F
    FINISHED
  Downloading https://s3.amazonaws.com/cie-fueled-racing-cdn/logs/2013-07-26-01-37-41-28575F05246E0003
    FINISHED
  Downloading https://s3.amazonaws.com/cie-fueled-racing-cdn/logs/2013-07-26-01-44-45-AD0A5F79BE99EABB
    FINISHED

Maybe copy paste the error into here?

The actual download code has a try/except around it.  The only other stuff is directory creation if required.

**Comment by Ucnt** [comment]
You did bring up a great idea that I just added though.
There is now a "--last_key" argument that you can add, e.g. "logs/" to skip ahead to that portion.

**Comment by TechXPlays** [comment]
I was going to convert all this to a C# form based tool with the options built in, just haven't had time, but that was something I thought of adding, should have put it here sooner when I thought of it... As for the error, if they pop up again, i'll add them to this post

**Comment by Ucnt** [comment]
Sounds good.  Closing for now then.
